#pragma once

#include <Cor/BaseTypes.hh>

#define ORDO_INVALID_INDEX U32_MAX
#define ORDO_INFINITE U32_MAX
#define ORDO_STEAL_PROBE_COUNT 4u
#define ORDO_COMPLETION_FLUSH_THRESHOLD 256u
#define ORDO_COUNTER_COMPLETION_FLUSH_THRESHOLD 256u 
#define ORDO_FIBER_MAX_NUM_HOT_REUSES 32u
#define ORDO_MAX_INJECTION_CHUNK_SIZE 4096u
